plugins {
	id 'dev.architectury.loom' version '1.6-SNAPSHOT'
}

loom {
	silentMojangMappingsLicense()
	forge {
		mixinConfig "template_mod.mixins.json"
	}
}

group = project.findProperty('maven_group') ?: 'com.example.template'
version = '1.0.0-template-1.20.1'

repositories {
	mavenCentral()
	maven { url = 'https://maven.minecraftforge.net/' }
	maven { url = 'https://maven.architectury.dev/' }
	maven { url = 'https://cursemaven.com' }
	maven { url = 'https://api.modrinth.com/maven' }
}

dependencies {
	minecraft "com.mojang:minecraft:1.20.1"
	mappings loom.officialMojangMappings()
	forge "net.minecraftforge:forge:1.20.1-${project.findProperty('forge_version') ?: '47.3.0'}"
	modApi "dev.architectury:architectury-forge:9.2.14"
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release = 17
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
	withSourcesJar()
}

tasks.named('processResources', org.gradle.language.jvm.tasks.ProcessResources).configure {
	def replaceProperties = [
		minecraft_version: '1.20.1',
		minecraft_version_range: '[1.20.1,1.21)',
		forge_version: project.findProperty('forge_version') ?: '47.3.0',
		forge_version_range: '[47,48)',
		loader_version_range: '[47,)',
		mod_id: 'template_mod',
		mod_name: 'Template Mod',
		mod_version: project.version,
		mod_authors: 'YYH',
		mod_description: 'Template Mod for Forge'
	]

	inputs.properties replaceProperties

	filesMatching(['META-INF/mods.toml']) {
		expand replaceProperties
	}
}

tasks.withType(JavaExec).configureEach {
	javaLauncher = javaToolchains.launcherFor {
		languageVersion = JavaLanguageVersion.of(17)
	}
	systemProperty 'minecraft.username', rootProject.findProperty('minecraft_username') ?: 'Player'
}