org.gradle.jvmargs=-Xmx3G -Djava.net.preferIPv4Stack=true
org.gradle.parallel=true

# Gradle User Home redirected to project gradle_home directory
gradle.user.home=gradle_home

# Minecraft & Forge Properties
minecraft_version=1.20.1
forge_version=47.3.0

# Mod Properties
mod_id=template_mod
mod_name=Template Mod
mod_version=1.0.0
mod_authors=YYH
mod_description=Template Mod for Forge
maven_group=com.example.template

# Run Properties
minecraft_username=Developer